print("Giraffe\nAcademy")
print("Giraffe\"Academy")
print("Giraffe\Academy")
phase = "Giraffe Academy"
print(phase + "is cool")
print(phase.lower())
print(phase.upper())
print(phase.upper().isupper())
print(len(phase))
print(phase[0])
print(phase[1])
print(phase[2])
print(phase[7])
print(phase[8])
print(phase.index("G"))
print(phase.index("a"))
print(phase.index("ff"))
print(phase.replace("Giraffe","Elephant"))

