name = input("Enter your name: ")
print("Hello " + name + ',' + " nice to meet you !")
age =input("How old are you ? ")
print("All of my friends are also " + age + ".")
school = input("Which school are you in ? ")
print("Cool, I also study in " + school + "." )
major =input("What is your major subject ? ")
print(major + " is also my favourite subject. ")
do = input("What are you doing rightnow ? ")
print("I am " + do + " like you, too. ")
print("I'm glad to see you today, bye and see you later. ")